[project]
name = "nsqip-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.13.15",
    "matplotlib>=3.10.3",
    "nsqip-tools>=0.1.0",
    "polars>=1.30.0",
    "seaborn>=0.13.2",
]
